# 5.6 Greenhouse Gas Emissions

## Purpose of indicator

Relevant for global climate mitigation goals (Paris Agreement) and nationally determined contributions (NDCs).

## Key Metadata

| Metadata Item     | Description                                                      |
|-------------------|------------------------------------------------------------------|
| Indicator Name    | Greenhouse gas emissions |
| Theme             | Climate mitigation |
| SDGs Targeted     | Paris Agreement, NDCs |
| Data Source       | Farmer survey, literature review, and/or field measurements |
| Measurement       | Emissions of nitrous oxide, methane and CO₂ (the main greenhouse gases, GHGs) minus carbon storage and sequestration by above-ground biomass |
| Measurement Units | t C ha⁻¹ yr⁻¹ |

## Guidance on Measurement

**Measuring GHG emissions**

We discuss two options for measurement, i) using emission factors, ii) direct measurement.

*Using emission factors*

This method is based on guidelines provided by the Intergovernmental Panel on Climate Change (IPCC 2006). GHGs are estimated by multiplying the activity data for the activity of interest with emission factors.

To apply this approach in estimating GHGs, the activity data for the area of interest needs to be well documented. This can be done as part of the household survey and supplemented with information from literature. For example, to estimate direct N₂O emissions from agricultural soils in a certain region, one would require information on the use of fertilizers and manure, amount of N fixed by crops, amount of crop residues returned to soils, N-fixing crops, area of the cultivated crop and two emission factors, i.e. one for N inputs into soil and one for cultivation of organic soils. Detailed guidelines, examples, and training materials on how to apply the emission factors methodology to estimate GHGs can be found in the Non-Annex I training package (<https://unfccc.int/resource/cd_roms/na1/ghg_inventories/index.htm>).

For livestock, much of the information required to calculate GHG emissions will be collected as part of the Animal health and welfare survey.

**Step-by-step procedure:**

1. Within the area of study (e.g. the ALL), identify the major land uses, crops and livestock species.

2. For each crop and livestock species selected, gather spatially-explicit management information (plot level information for crops and individual animal level information for livestock) together with associated soil and climatic information. Include as many plots/livestock number as possible to make the data representative for the area of interest.

3. Gather total crop area and livestock number (segregated by type, breed, sex, age etc) within the smallest geographical unit (e.g. district)

4. By using the management information collected in step 2, use the IPCC tier 1 emission factors co-efficients to estimate the emissions.

*Direct measurement*

For direct measurement of greenhouse gas emissions at farm level, use the "Static chamber method" and procedures as described in Rosenstock et al. (2016).

Briefly, the chambers, made of plastic and of known dimensions are inserted into the soil to certain depths (forming bases), approximately one week before planting. About 3-5 chamber bases are inserted per plot per replicate. Base height dimensions are taken, the bases are then covered with special lids (vented, fitted with thermometers, fans, batteries and gas sampling ports) and are tightly clamped. Gas samples are collected following certain considerations (i.e., timing, intervals, storage, etc) and taken to the laboratory for gas chromatography (GC) analysis to detect the three GHG (nitrous oxide, methane and CO₂).

Sampling requires some level of skills/expertise, i.e., drawing the gas from the chambers using the syringes should not be rushed but also not be done too slowly. When transferring the gases to the vials (evacuated) from the syringes, part of the gas (about 30 mls) should be used to push out the pre-existing gases in those vials and the remaining 30 ml retained in the tightly sealed vial (this is the one taken to the lab for GC). Training will be needed for these procedures, which will need just one day.

## Guidance on Data Entry and Reporting

**Direct measurement at plot level**

For direct plot measurements, proper frequency of gas sampling should be observed; guided by the prevailing environmental conditions. Under normal conditions, sampling should be done once per week. However, the frequency of sampling can be increased to 2 times per week under periods of expected high emissions in the field e.g., after rainfall, fertilization or soil disturbances like weeding. Sampling should be done between 9am to noon. In each sampling activity from the plot level, the following data should be entered:

Name of recorder, Date of sampling; Land use type; Name of site/experiment; Plot number; Air temperature and Air pressure. 3-4 chambers can be used per plot. In each of the 3 or 4 chambers bases installed, record the chamber heights (h1, h2, h3 and h4). When sampling begins, for each chamber base, record the start temperature (T1) and the stop temperature (T4) for every chamber. In each chamber, gas withdrawal (sampling) intervals can be timed at either 10 or 15 minutes, or what is feasible. Gas samples should be taken at 4 time intervals, starting from T0. At every time interval (i.e., T0, T15, T30 or T45 mins), record the start time, stop time and properly label the gas vial after transferring the gas sample. Other additional parameters to record would be the soil moisture and soil temperature per plot in every sampling activity.

The measurement unit is t C ha⁻¹ yr⁻¹.

## Calculation Method

_no information is available_

## Indicator Interpretation and Threshold Setting

_no information is available_

## Limitations

_no information is available_

## References

- Rosenstock et al. (2016)
- IPCC 2006, 2006 IPCC Guidelines for National Greenhouse Gas Inventories, Prepared by the National Greenhouse Gas Inventories Programme, Eggleston H.S., Buendia L., Miwa K., Ngara T. and Tanabe K. (eds). Published: IGES, Japan.
- <https://unfccc.int/resource/cd_roms/na1/ghg_inventories/index.htm>
- <https://www.ipcc-nggip.iges.or.jp/public/2019rf/vol4.html>
- <https://www.ipcc-nggip.iges.or.jp/public/2019rf/index.html>
