# 3.2 Land tenure security

## Purpose of indicator

Land access is closely linked to use and control over productive resources. Secure land tenure is therefore a key determinant of individual agency, income and wellbeing. This indicator is aligned with SDG 1.4.2 and 5.a.1.

## Key Metadata

| Metadata Item     | Description                                                      |
|-------------------|------------------------------------------------------------------|
| Indicator Name    | Land tenure security |
| Theme             | Land tenure |
| SDGs Targeted     | SDG 1.4.2, SDG 5.a.1 |
| Data Source       | Parcels (most preferable) or household/farm (most possible) survey using a simplified version of the harmonized questionnaire proposed by FAO et al. (2019). Additionally, GPS delineation of parcels is strongly advised wherever feasible, as evidence points to systematic bias in farmer estimates of land area (Carletto, 2021). |
| Measurement       | ((Area of agricultural land used by the household for which at least one member of the household has their name on a legally recognized document OR has the right to sell OR has the right to bequeath)/(Total land area used by the household))*100 |
| Measurement Units | % |

## Guidance on Measurement

The indicator can be calculated with data collected using FAO's harmonized questionnaire, which is a standardized and succinct survey instrument designed to collect the essential data for computation of both 1.4.2 and 5.A.1 Sustainable Development Goals (SDGs) indicators simultaneously.

The methodology proposed 5 versions of the questionnaire depending on: (i) the respondent selection approach, (ii) whether or not the survey collects data at the parcel-level and (iii) whether or not the existing survey includes a parcel roster. Each version of the questionnaire has approximated 10 questions and assumes that a separate household member roster exists and that the sex of each household member is captured in that roster.

Where possible, it is advised to have parcel level data and implement a self-respondent approach (i.e., where individuals respond for themselves only, not on behalf of others) (version 2 with 7 questions). Where it is not, land tenure data should be collected at the household/farm level, using the version 3 (13 questions) of the questionnaire.

A sub-indicator can be calculated as: ((Number of adult women in agricultural households whose name is on a legally recognized document OR who have the right to sell OR bequeath agricultural land)/(Total adult individuals in agricultural households whose name is on a legally recognized document OR who have the right to sell OR bequeath agricultural land))*100.

Note, for pastoralists, land tenure security may be better measured in terms of mobility, i.e. proportion of grazing lands over which the farmer has unrestricted rights to graze livestock.

**Guidance on how to apply the questionnaire:**

- The survey should be completed for the adult household member (18 years old or older).
- Because a self-respondent approach is going to be used and only some (or one) randomly selected household members are interviewed about their tenure rights, only the selected members are part of the reference population (i.e., denominator in the indicator and sub-indicator formulas).
- The country-specific questionnaire should include: i) a comprehensive list of all tenure types applicable to the country; ii) a comprehensive list of land tenure-related documents, specifying which ones the government considers as legally recognized; iii) images of the documents considered legally recognized; iv) a context-specific definition of alienation rights.

SDG 1.4.2: Proportion of total adult population with secure tenure rights to land, with (a) legally recognized documentation; and (b) who perceive their rights to land as secure, by sex and by type of tenure.

SDG 5.a.1: (a) proportion of total agricultural population with ownership or secure rights over agricultural land by sex; and (b) share of women among owners or rights bearers of agricultural land, by type of tenure.

## Guidance on Data Entry and Reporting

Check that the total land area accessed by the household matches the sum of the land areas with different access types.

## Calculation Method

```{.r
        include="../../holpa-r-scripts/data_processing/key_performance_indicators.R"
        snippet="3.2.land_tenure"
        code-line-numbers="true"
    }
```

## Indicator Interpretation and Threshold Setting

_no information is available_

## Limitations

_no information is available_

## References

- [@fao2019tape]
